### ISSUE TITLE
Unable to start surepetcarebeta - version 117d92a 

### ISSUE THREAD

**Issue by axa4953** [benleb/surepetcare#3]
Running HA OS 2021.05.0

### Activities/Update
Performed Git pull via HACS, version 117d92a
Set/updated parameters in configuration.yaml

From:
```
#SurePetCare
surepetcare:
  username: !secret my_email_address
  password: !secret surepetcare_password
```

To:
```
#SurePetCare
surepetcarebeta:
  username: !secret my_email_address
  password: !secret surepetcare_password
```

### Issue/Experience:
When executing "configuration validation" in HA Supervisor, am presented with error message:
```Component error: surepetcarebeta - cannot import name 'SurePetcareAPIError' from 'surepy.exceptions' (/usr/local/lib/python3.8/site-packages/surepy/exceptions.py)```

Forced restart of HA Supervisor nevertheless, and am presented with errors in log:

![image](https://user-images.githubusercontent.com/34874748/117611939-b3da1200-b1a7-11eb-8098-17252e0404c9.png)

Additional tests performed:
a.) full removal of HACS history of surepetcare (and restarted HA Supervisor)
b.) removal of surepetcare credentials in configuration.yaml (and restarted HA Supervisor)
c.) removal of old entities  (and restarted HA Supervisor)
d.) removal of any old custom_components folders related to "surepetcare" (and restarted HA Supervisor)

Finally:
e.) Performed installation steps as per guide here 

--> Result is more or less the same. Surepetcarebeta does not seem to allow integration with existing surepy libraries in HA in my case. 

Cheers
