### ISSUE TITLE
Cat lefts the house without recognition

### ISSUE THREAD

**Issue by Pr0mises** [benleb/surepetcare#32]
Hey all,
I've only one cat that's leaving the house pretty fast, the sensor can't keep up and doesn't recognize the cat name.
In the official app I get a notification with "An animal has left the house through the device <flap_name>"..

Is it possible to add an entity with that information as well, so I can change its position according to the log?

**Comment by xbmcnut** [comment]
If you use the Home Assistant mobile app you might be able to pull that info like this as I did once.
```
  - alias: "Announce when Kobi comes in"
    id: 14c30678-8aa5-4a3a-a112-7c72879a71e0
    trigger:
      platform: state
      entity_id: sensor.pete_s_pixel_3_last_notification
      to: 'Kobi has entered through Laundry Door... Hi Kobi!'
    action:
      - service: media_player.play_media
        data_template:
           entity_id:
             - media_player.lounge_home
```
