### ISSUE TITLE
Feeders no longer report values

### ISSUE THREAD

**Issue by robertgetch** [benleb/surepetcare#52]
After the recent break due to Sure Petcare's API changes I no longer receive the values for remaining pet food in the two SurePet Feeders I have; the two feeders both report "unknown" and do not update. The SurePet app is correctly updating the values indicating that the feeders are still communicating and the hub is reporting to the cloud.

I have removed the integration, restarted the Sure Pet Hub, restarted the feeders and reinstalled the integration after rebooting HA. I am using the latest HA version which has resolved the issues with the Cat Flap and allowing me to lock/unlock the Cat Flap again and that all seems to work correctly (thank you!).

I cannot find anything in the logs (including after enabling debug logging and downloading the corresponding log file) that seems to indicate that its failing somewhere, it just seems like the updates are either no longer being provided. When the integration first loads it does pull a variety of attributes for the feeder that are correct, everything except the remaining food amount. After that point though it never updates again, and the remaining food value is never pulled. 

Please let me know how I can assist in correcting this integration bug! Happy to help as I can.

**Comment by blair287** [comment]
Same issue my felaqua is working though but nothing for feeders. @benleb was something maybe missed with the json thing or does sureha need updating too?

**Comment by blair287** [comment]
Now the integration is broken completely again can sign in the but fails to initialize and finds no devices

**Comment by blair287** [comment]
> After the recent break due to Sure Petcare's API changes I no longer receive the values for remaining pet food in the two SurePet Feeders I have; the two feeders both report "unknown" and do not update. The SurePet app is correctly updating the values indicating that the feeders are still communicating and the hub is reporting to the cloud.
> 
> I have removed the integration, restarted the Sure Pet Hub, restarted the feeders and reinstalled the integration after rebooting HA. I am using the latest HA version which has resolved the issues with the Cat Flap and allowing me to lock/unlock the Cat Flap again and that all seems to work correctly (thank you!).
> 
> I cannot find anything in the logs (including after enabling debug logging and downloading the corresponding log file) that seems to indicate that its failing somewhere, it just seems like the updates are either no longer being provided. When the integration first loads it does pull a variety of attributes for the feeder that are correct, everything except the remaining food amount. After that point though it never updates again, and the remaining food value is never pulled.
> 
> Please let me know how I can assist in correcting this integration bug! Happy to help as I can.

Any of your stuff start working? Mine still all unknown :(

**Comment by robertgetch** [comment]
The locations continue to work but the feeders continue to be unknown.

**Comment by chrannen** [comment]
@blair287 

> Now the integration is broken completely again can sign in the but fails to initialize and finds no devices

Which version of HA are you using? I'm using 2023.12.4 and haven't noticed any problems. In addition to the hub, I have 2 flaps in use and 2 pets involved. Are you using version 2024.1.x? Or are you only having problems with the feeders?

**Comment by robertgetch** [comment]
The problem only exists with the Feeders and apparently the Feliaqua.

**Comment by chrannen** [comment]
> Das Problem besteht nur bei den Feedern und offenbar auch bei der Feliaqua.

Ahh, OK, thanks. That's why i don't notice any problems.

**Comment by jafrouk** [comment]
I recnetly installed the integration on a fresh install of Home Assistant, and one of the things I remember being there before that isn't there now is the level of the food in the bowls ( I was also trying to follow https://github.com/home-assistant/core/issues/93003#issuecomment-1633351764 that @magicmega posted, and don't see the _bowl_0 and _bowl_1 entities I was expecting either).  

Is this related?

**Comment by blair287** [comment]
My felaqua suddenly started working but feeders are still unknown.

**Comment by Anaxagoras-bc** [comment]
I am having the same issue with the feeders.

**Comment by blair287** [comment]
@benleb any ideas on what's broken tje feeders?

**Comment by blair287** [comment]
Wish I knew how to code for this :( so could create a pull request or fork it not sure this will get fixed anytime soon sorry guys.

**Comment by magicmega** [comment]
All working for me now; I have put in a workaround that joins the data where it shows up as unknown (uses last known value). I can find and post it if others want it

**Comment by MechEng70** [comment]
Please post it.  TIA

**Comment by blair287** [comment]
> All working for me now; I have put in a workaround that joins the data where it shows up as unknown (uses last known value). I can find and post it if others want itSent from my iPhoneOn 27 Jan 2024, at 2:10 pm, blair287 ***@***.***> wrote:﻿ Wish I knew how to code for this :( so could create a pull request or fork it not sure this will get fixed anytime soon sorry guys. —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

Yes please post

**Comment by magicmega** [comment]
**Coping with the feeder state going to unknown at random times:**

I've set up a proxy variable (var) for each bowl state, that only updates when there is a real value in the actual bowl state (i.e. skips changes to 'unknown'.

I have two feeders for two cats, each with two bowls (1 dry, 1 wet) in the feeder. I've set up the following for each bowl (i.e. 4x the below code)

```
- id: '[yours here]'
  alias: Luna dry food update
  description: ''
  trigger:
  - platform: state
    entity_id:
    - sensor.feeder_lunas_bowl_bowl_0
  condition:
  - condition: template
    value_template: '{{ trigger.from_state.state not in [''unknown'', ''unavailable'']
      }}'
  - condition: template
    value_template: '{{ trigger.to_state.state not in [''unknown'', ''unavailable'']
      }}'
  - condition: template
    value_template: '{{ trigger.from_state.state != trigger.to_state.state}}'
  action:
  - service: var.update
    data:
      entity_id: var.luna_dry_bowl_sans_unknown
  mode: single
```

The variables are set up as follows

(in var: file)
```
luna_dry_bowl_sans_unknown:
  friendly_name: 'Luna dry food bowl weight (cope with unknowns)'
  initial_value: 0
  unique_id: 'lunadryfoodsansunknown'
  value_template: "{{states('sensor.feeder_lunas_bowl_bowl_0')}}"
  icon: mdi:cat
  unit_of_measurement: g
```
