### ISSUE TITLE
b5d324e reports lock states without an underscore

### ISSUE THREAD

**Issue by xbmcnut** [benleb/surepetcare#8]
Hi there,

Love this integration although it did make me go out and buy a $300 cat door!

Just letting you know that the b5d324e beta I'm running seems to be working well except the underscore has been removed from the lock states so most of my code in HA is not working correctly. If possible, could the locks states all be changed to lowercase with an underscore in between?

![image](https://user-images.githubusercontent.com/1492137/117927388-40263980-b34e-11eb-86d8-5a906292e4a9.png)

**Was:**
```
    condition:
      - condition: state
        entity_id: sensor.pet_flap_laundry_door
        state: 
          - Locked_all
          - Locked_in
          - Locked_out
    action:
      - service: surepetcare.set_lock_state
        data_template:
```
**Current Beta (b5d324e):**
```
    condition:
      - condition: state
        entity_id: sensor.pet_flap_laundry_door
        state: 
          - Locked All
          - Locked In
          - Locked Out
    action:
      - service: surepetcare.set_lock_state
        data_template:
```
**Ideal:**
```
    condition:
      - condition: state
        entity_id: sensor.pet_flap_laundry_door
        state: 
          - locked_all
          - locked_in
          - locked_out
    action:
      - service: surepetcare.set_lock_state
        data_template:
```
